### ISSUE TITLE
Add license for the osquery-crowdstike-ext table extension

### ISSUE THREAD

**Issue by nonpunctual** [bdemetris/osquery-crowdstrike-ext#5]
Hi Brett -

Would it be possible for you to add a license to this repo (e.g., the MIT or some permissive license of your choosing?) Fleet would like to include this extension in our open source repo but can't without there being some sort of license for your work. I assume that since you made it public this would be acceptable to you. 

However, if you don't wish to add a license, no problem. Thanks for your consideration!

**Comment by bdemetris** [comment]
done https://github.com/bdemetris/osquery-crowdstrike-ext/pull/6

**Comment by nonpunctual** [comment]
Thanks again!
